name: 04 Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: npm ci
        working-directory: 04-using-actions/react-app

      - name: Run Unit Test
        run: |
          cd 04-using-actions/react-app
          npm run test
