name: 05-1-Event-Filters-And-Activity-Types

on:
  pull_request:
    types: closed
    branches:
      - main

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is closed AND base branch is main"
