run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

name: 06-Contexts

on:
  #   push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
env:
  MY_WORKFLOW_VAR: 'workflow'
  MY_OVERWRITTEN_VAR: 'workflow'

jobs:
  echo-data:
    runs-on: ubuntu-latest
    env:
      MY_JOB_VAR: 'job'
      MY_OVERWRITTEN_VAR: 'job'
    steps:
      - name: Display Information
        run: |
          echo "Event name: ${{ github.event_name}}"
          echo "Ref: ${{github.ref_name}}"
          echo "SHA: ${{ github.sha}}"
          echo "Actor: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow}}"
          echo "Run ID: ${{github.run_id}}"
          echo "Run number: ${{ github.run_number}}"
          echo "Repository Name: ${{ github.repository}}"

      - name: Retrieve Variable
        run: |
          echo "Variable Name: ${{ vars.MY_VAR }}"

      - name: Print Env Variables
        env:
          MY_OVERWRITTEN_VAR: 'step'
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR}}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR}}"

      - name: Print Env Vars
        run: |
          echo "Workflow env: ${{ env.MY_WORKFLOW_VAR}}"
          echo "Overwritten env: ${{ env.MY_OVERWRITTEN_VAR}}"
