name: 12 Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{steps.build.outputs.status}}
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo $GITHUB_OUTPUT
      - name: Build
        id: build
        run: echo "status=${{inputs.build-status}}" >> "GITHUB_OUTPUT"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{needs.build.outputs.build-status == 'success'}}
    steps:
      - name: Deploy
        run: echo "Deploying"
