name: 17 - 1 - Custom Actions - Composite

run-name: 17 - 1 - Custom Actions - Composite | env - ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: choice
        options:
          - prod
          - dev
env:
  working-directory: apps/react-app

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{env.working-directory}}

    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: ${{env.working-directory}}
          target-env: ${{inputs.target-env}}

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
