name: 17 - 2 - Custom Actions-JS

run-name: '17-2-Custom-Actions-JS - BB: ${{inputs.base-branch}} - TB: ${{inputs.target-branch}} - WD: ${{inputs.working-dir}} '

on:
  workflow_dispatch:
    inputs:
      base-branch:
        type: string
        default: main

      target-branch:
        type: string
        default: update-dependencies

      working-dir:
        type: string
        default: apps/react-app

      debug:
        description: Whether the output debug messages to the console
        required: false

permissions:
  contents: write
  pull-requests: write

jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
        id: update-deps
        with:
          base-branch: ${{inputs.base-branch}}
          target-branch: ${{inputs.target-branch}}
          working-directory: ${{inputs.working-dir}}
          debug: ${{inputs.debug}}
          gh-token: ${{secrets.GITHUB_TOKEN}}
      - name: Print custom action output
        run: |
          echo "Updates available: ${{ steps.update-deps.outputs.updates-available }}"
