name: 17 - 3 - custom actions - docker

on:
  workflow_dispatch:
    inputs:
      url:
        type: choice
        options:
          - https://www.facebook.com
          - https://www.gydcdj.net.xy
        default: 'https://www.google.com'

      max_trials:
        description: Maximum trials until action fails
        default: '10'

      delay:
        description: Delay in seconds between trials
        default: '5'

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          url: ${{inputs.url}}
          max_trials: ${{inputs.max_trials}}
          delay: ${{inputs.delay}}
