name: 20 - workflow-security

on: pull_request

jobs:
  unsafe-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Check PR title
        run: |
          title=${{ github.event.pull_request.title }}
          if [[ $title =~ ^feat ]]; then
          echo "PR is a feature. Ha ha!"
          exit 0
          else
          echo "PR is not a feature"
          exit 1
          fi
